language: ruby
rvm:
  # see https://www.ruby-lang.org/en/downloads/branches/
  - ruby-head
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  # NOTE: EOL since 2019-03-31
  - 2.3
  # see https://www.jruby.org/download
  - jruby-9.1
  - jruby-9.2
  - truffleruby
# Freezing the JDK to provide some consistency between CI builds only.
jdk:
  - openjdk8
